// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test1 {
	
	
	public partial class Create {
		
		protected System.Web.UI.HtmlControls.HtmlForm form10;
		
		protected System.Web.UI.WebControls.Button buttonTest;
		
		protected System.Web.UI.WebControls.Label outputlabelTest;
		
		protected System.Web.UI.HtmlControls.HtmlForm form11;
		
		protected System.Web.UI.WebControls.Button buttonRetour;
		
		protected System.Web.UI.WebControls.Label outputlabelRetour;
	}
}
