// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test1 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form21;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile TextboxBegin;
		
		protected System.Web.UI.WebControls.Button buttonBegin;
		
		protected System.Web.UI.HtmlControls.HtmlForm form30;
		
		protected System.Web.UI.WebControls.TextBox TextboxProjet;
		
		protected System.Web.UI.WebControls.Button buttonProjet;
		
		protected System.Web.UI.HtmlControls.HtmlForm form20;
		
		protected System.Web.UI.WebControls.TextBox TextboxStart;
		
		protected System.Web.UI.WebControls.Button buttonStart;
		
		protected System.Web.UI.HtmlControls.HtmlForm form22;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Button button2;
		
		protected System.Web.UI.WebControls.Label outputlabel2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form3;
		
		protected System.Web.UI.WebControls.Button button3;
		
		protected System.Web.UI.WebControls.Label outputlabel3;
		
		protected System.Web.UI.HtmlControls.HtmlForm form4;
		
		protected System.Web.UI.WebControls.Button button4;
		
		protected System.Web.UI.WebControls.Label outputlabel4;
	}
}
