// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test1 {
	
	
	public partial class Update {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Button button2;
		
		protected System.Web.UI.WebControls.Label outputlabel2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form3;
		
		protected System.Web.UI.WebControls.Button buttonRetour;
	}
}
